### ISSUE TITLE
Doesn't work for TBC if you don't delete Vanilla toc

### ISSUE THREAD

**Issue by Macumbafeh** [shagu/ShaguMail#1]
Heyo !

I wanted to try your addon, but first time i tried => Nothing happened.
The addon was in  addon windows. but was incompatible.

I opened the folder addon, and i saw 2 .toc files O_o.
And the Vanilla one was detected first. So i delete the Vanilla one et renamed the TBC one. 
and it worked. Maybe make 2 differents link for vanilla/TBC?

ty !

**Comment by shagu** [comment]
Just read the readme. It clearly states: 
> Rename the folder "ShaguMail-master" to "ShaguMail-tbc"

This is because the game always loads the toc that has the same name as the folder name.

**Comment by Macumbafeh** [comment]
I'm talking about the .toc files inside.
you have to delete the vanilla .toc and rename the TBC .toc "Shagumail" instead of Shagumail-tbc.
Then it worked.


Edit : i understood now. If you rename the folder you don't have to do that. ^^'
