### ISSUE TITLE
Stop opening all after closing mailbox

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguMail#2]
I push the "Open All" button, and when I consider that it opened enough mails, I close the mailbox (or I get far enough from it so it closes automatically).
But then, when I open the mailbox again, it continues opening all mails.
That means there is no way to stop the process once you start it.
The only option is to log off - or to wait until all the inbox is full and then it stops.

I am using [Mail](https://github.com/shirsig/Mail) addon on vanilla and when you close the mailbox, it stops so when I open the mailbox will not continue opening all

**Comment by shagu** [comment]
Thanks for your report, fixed by this commit: https://github.com/shagu/ShaguMail/commit/3071dbc060488f69bd7f6c47a6691f4492634b0b
